Standardize on PyTorch for machine learning models
tue-robotics/image_recognition pull request #146
Opened 2022-02-05 14:26 UTC by LoyVanBeek

- [ ] Age & Gender recognition

2022-02-06 13:09 UTC, MatthijsBurgh requested changes

2022-02-06 13:09 UTC, MatthijsBurgh commented on image_recognition_pytorch/README.md
> +# Keras image recognition
Replace all Keras in this document

2022-02-06 13:09 UTC, MatthijsBurgh commented on image_recognition_pytorch/test/run_tests.bash
> +nosetests -vv "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
Why is this needed? Just for manual testing? As we use the catkin macro.

2022-02-07 07:20 UTC, LoyVanBeek commented on image_recognition_pytorch/README.md
> +# Keras image recognition
Crap, I thought I had it all

2022-02-07 09:59 UTC, MatthijsBurgh commented
Also we should include `python3-onnxruntime-pip` in rosdistro

2022-02-26 10:07 UTC, MatthijsBurgh requested changes
Fix catkin lint
```
image_recognition_pytorch: package.xml: error: unknown package 'python3-onnxruntime-pip'
image_recognition_pytorch: package.xml: error: unknown package 'python3-pytorch-pip'
image_recognition_pytorch: warning: file 'scripts/download_model' is executable but not installed
image_recognition_pytorch: package.xml: notice: meaningless package description 'The image_recognition_pytorch package'
catkin_lint: checked 1 packages and found 4 problems
```

2022-03-09 12:06 UTC, closed without merging