updated scripts and src facenet model according to code review
tue-robotics/image_recognition pull request #223
Opened 2024-03-12 20:40 UTC by iasonth95

2024-04-23 17:45 UTC, P-ict0 approved these changes

2025-02-14 07:33 UTC, MatthijsBurgh requested changes

2025-02-14 07:33 UTC, MatthijsBurgh commented on image_recognition_face_recognition/test/test_import.py
> +class TestFaceRecognizer(unittest.TestCase):
You shouldn't delete my test. You should have created a new file with (a) new testcase(s)

2025-02-14 09:18 UTC, iasonth95 commented on image_recognition_face_recognition/src/image_recognition_face_recognition/facenet_recognition.py
> +        self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
done

2025-02-14 09:44 UTC, MatthijsBurgh requested changes

2025-02-14 09:44 UTC, MatthijsBurgh commented on image_recognition_face_recognition/scripts/face_recognition_node
> +        num_gpu_start
This should be device as it can also be cpu...

2025-02-14 09:57 UTC, iasonth95 commented on image_recognition_face_recognition/test/test_import.py
> +class TestFaceRecognizer(unittest.TestCase):
I import the library that your test was asserting thats why i removed it. Should i add it back ?

2025-02-14 10:03 UTC, iasonth95 commented on image_recognition_face_recognition/scripts/face_recognition_node
> +        num_gpu_start
done

2025-02-24 08:19 UTC, merged